/* EIC configuration for KSZ8851SNL interrupt support */
#ifndef HPL_EIC_CONFIG_H
#define HPL_EIC_CONFIG_H

// Basic Settings
#define CONF_EIC_CKSEL 0
#define CONF_EIC_TICKON 0

// Non-Maskable Interrupt Control (disabled)
#define CONF_EIC_ENABLE_NMI_CTRL 0
#define CONF_EIC_NMIFILTEN 0
#define CONF_EIC_NMISENSE EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_NMIASYNCH 0

// Interrupt 0-6 Settings (all disabled)
#define CONF_EIC_ENABLE_IRQ_SETTING0 0
#define CONF_EIC_FILTEN0 0
#define CONF_EIC_DEBOUNCE_ENABLE0 0
#define CONF_EIC_EXTINTEO0 0
#define CONF_EIC_SENSE0 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH0 0

#define CONF_EIC_ENABLE_IRQ_SETTING1 0
#define CONF_EIC_FILTEN1 0
#define CONF_EIC_DEBOUNCE_ENABLE1 0
#define CONF_EIC_EXTINTEO1 0
#define CONF_EIC_SENSE1 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH1 0

#define CONF_EIC_ENABLE_IRQ_SETTING2 0
#define CONF_EIC_FILTEN2 0
#define CONF_EIC_DEBOUNCE_ENABLE2 0
#define CONF_EIC_EXTINTEO2 0
#define CONF_EIC_SENSE2 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH2 0

#define CONF_EIC_ENABLE_IRQ_SETTING3 0
#define CONF_EIC_FILTEN3 0
#define CONF_EIC_DEBOUNCE_ENABLE3 0
#define CONF_EIC_EXTINTEO3 0
#define CONF_EIC_SENSE3 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH3 0

#define CONF_EIC_ENABLE_IRQ_SETTING4 0
#define CONF_EIC_FILTEN4 0
#define CONF_EIC_DEBOUNCE_ENABLE4 0
#define CONF_EIC_EXTINTEO4 0
#define CONF_EIC_SENSE4 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH4 0

#define CONF_EIC_ENABLE_IRQ_SETTING5 0
#define CONF_EIC_FILTEN5 0
#define CONF_EIC_DEBOUNCE_ENABLE5 0
#define CONF_EIC_EXTINTEO5 0
#define CONF_EIC_SENSE5 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH5 0

#define CONF_EIC_ENABLE_IRQ_SETTING6 0
#define CONF_EIC_FILTEN6 0
#define CONF_EIC_DEBOUNCE_ENABLE6 0
#define CONF_EIC_EXTINTEO6 0
#define CONF_EIC_SENSE6 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH6 0

// Interrupt 7 Settings (PB7 - KSZ8851SNL INT pin)
#define CONF_EIC_ENABLE_IRQ_SETTING7 1

// External Interrupt 7 Filter Enable
#define CONF_EIC_FILTEN7 0

// External Interrupt 7 Debounce Enable (disable for performance)
#define CONF_EIC_DEBOUNCE_ENABLE7 0

// External Interrupt 7 Event Output Enable
#define CONF_EIC_EXTINTEO7 0

// Input 7 Sense Configuration - Falling edge detection (KSZ8851SNL INT is active low)
#define CONF_EIC_SENSE7 EIC_NMICTRL_NMISENSE_FALL_Val

// External Interrupt 7 Asynchronous Edge Detection Mode
#define CONF_EIC_ASYNCH7 0

// Interrupt 8-15 Settings (all disabled)
#define CONF_EIC_ENABLE_IRQ_SETTING8 0
#define CONF_EIC_FILTEN8 0
#define CONF_EIC_DEBOUNCE_ENABLE8 0
#define CONF_EIC_EXTINTEO8 0
#define CONF_EIC_SENSE8 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH8 0

#define CONF_EIC_ENABLE_IRQ_SETTING9 0
#define CONF_EIC_FILTEN9 0
#define CONF_EIC_DEBOUNCE_ENABLE9 0
#define CONF_EIC_EXTINTEO9 0
#define CONF_EIC_SENSE9 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH9 0

#define CONF_EIC_ENABLE_IRQ_SETTING10 0
#define CONF_EIC_FILTEN10 0
#define CONF_EIC_DEBOUNCE_ENABLE10 0
#define CONF_EIC_EXTINTEO10 0
#define CONF_EIC_SENSE10 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH10 0

#define CONF_EIC_ENABLE_IRQ_SETTING11 0
#define CONF_EIC_FILTEN11 0
#define CONF_EIC_DEBOUNCE_ENABLE11 0
#define CONF_EIC_EXTINTEO11 0
#define CONF_EIC_SENSE11 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH11 0

#define CONF_EIC_ENABLE_IRQ_SETTING12 0
#define CONF_EIC_FILTEN12 0
#define CONF_EIC_DEBOUNCE_ENABLE12 0
#define CONF_EIC_EXTINTEO12 0
#define CONF_EIC_SENSE12 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH12 0

#define CONF_EIC_ENABLE_IRQ_SETTING13 0
#define CONF_EIC_FILTEN13 0
#define CONF_EIC_DEBOUNCE_ENABLE13 0
#define CONF_EIC_EXTINTEO13 0
#define CONF_EIC_SENSE13 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH13 0

#define CONF_EIC_ENABLE_IRQ_SETTING14 0
#define CONF_EIC_FILTEN14 0
#define CONF_EIC_DEBOUNCE_ENABLE14 0
#define CONF_EIC_EXTINTEO14 0
#define CONF_EIC_SENSE14 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH14 0

#define CONF_EIC_ENABLE_IRQ_SETTING15 0
#define CONF_EIC_FILTEN15 0
#define CONF_EIC_DEBOUNCE_ENABLE15 0
#define CONF_EIC_EXTINTEO15 0
#define CONF_EIC_SENSE15 EIC_NMICTRL_NMISENSE_NONE_Val
#define CONF_EIC_ASYNCH15 0

// Debouncer 0 Settings (for EXTINT[7:0])
#define CONF_EIC_DPRESCALER0 EIC_DPRESCALER_PRESCALER0(0x0)
#define CONF_EIC_STATES0 0x0

// Debouncer 1 Settings (for EXTINT[15:8])
#define CONF_EIC_DPRESCALER1 EIC_DPRESCALER_PRESCALER1(0x0)
#define CONF_EIC_STATES1 0x0

// Pin mapping for EXTINT7 -> PB07
#define CONFIG_EIC_EXTINT_MAP {7, PIN_PB07},

#endif // HPL_EIC_CONFIG_H